Repository UserOfficeProject/user-office-backend, pull requests merged in 2022-02, with the labels that each got.

#554 chore(npm): Removing unused packages
  package-lock.json
  package.json
Labels: chore

#555 fix: Send revised fields to EAM
  db_patches/db_seeds/0004_ScheduledEvents.sql
  src/auth/ShipmentAuthorization.ts
  src/config/dependencyConfigE2E.ts
  src/config/dependencyConfigESS.ts
  src/config/dependencyConfigSTFC.ts
  src/config/dependencyConfigTest.ts
  src/models/Shipment.ts
  src/mutations/FeedbackMutations.ts
  src/mutations/ShipmentMutations.ts
  src/queries/ScheduledEventQueries.ts
  src/resolvers/queries/ScheduledEventCoreQuery.ts
  src/resolvers/types/CommonWrappers.ts
  src/resolvers/types/ScheduledEvent.ts
  src/services/assetRegistrar/AssetRegistrar.ts
  src/services/assetRegistrar/eam/EAMAssetRegistrar.ts
  src/services/assetRegistrar/eam/api/createContainer.ts
  src/services/assetRegistrar/eam/api/createTicket.ts
  src/services/assetRegistrar/eam/api/getToken.ts
  src/services/assetRegistrar/eam/requests/AddAssetEquipment.ts
  src/services/assetRegistrar/eam/requests/AddCaseManagement.ts
  src/services/assetRegistrar/eam/utils/createAndLogError.ts
  src/services/assetRegistrar/eam/utils/getEnvOrThrow.ts
  src/services/assetRegistrar/eam/utils/performApiRequest.ts
  src/services/assetRegistrar/skip/SkipAssetRegistrar.ts
  src/services/eam/index.ts
  src/services/eam/requests/AddAssetEquipment.ts
Labels: bug

#541 fix(shipments): Add ability to declare multiple shipments per experiment time
  src/queries/ScheduledEventQueries.ts
Labels: bug

#556 fix: Questions using MCQ as a dependency not showing in PDF
  src/models/ConditionEvaluator.ts
  src/models/ProposalModelFunctions.spec.ts
Labels: bug

#553 Fixed the bug where User Officers could not add co-investigators to proposals
  db_patches/0116_CreateEmailSearchFeature.sql
  src/config/stfc/configureSTFCEnvironment.ts
  src/datasources/postgres/UserDataSource.ts
  src/datasources/stfc/StfcUserDataSource.ts
  src/models/Feature.ts
Labels: review: please

#559 feat: Add key directive to the Rejection to be able to reuse in scheduler
  src/queries/ScheduledEventQueries.ts
  src/resolvers/types/Rejection.ts
Labels: enhancement

#567 refactor: remove unused commissioning booking type from scheduler
  src/resolvers/types/ProposalBooking.ts
Labels: refactor

#558 feat: call start/end times
  db_patches/0116_AddTimezoneSetting.sql
  docker-compose.e2e.yml
  example.development.env
  src/asyncJobs/AsyncJobs.spec.ts
  src/asyncJobs/jobs/checkCallsEnded.ts
  src/config/ess/configureESSEnvironment.ts
  src/config/setTimezone.ts
  src/config/stfc/configureSTFCEnvironment.ts
  src/datasources/postgres/database.ts
  src/models/Settings.ts
Labels: enhancement, review: please

#569 fix: use right value for technical_review_assignee when creating the ProposalView model
  src/datasources/postgres/records.ts
Labels: bug, review: please
