Repository UserOfficeProject/user-office-backend, pull requests merged in 2022-08, with the labels that each got.

#706 refactor: Identifying facility using instrument attached to call
  src/eventHandlers/email/stfcEmailHandler.ts
Labels: review: please, refactor

#710 refactor: Add user profile URL to fix inconsistency
  src/config/stfc/configureSTFCEnvironment.ts
Labels: review: please, refactor

#717 refactor(graphql): rename query id params to have exact naming
  src/resolvers/queries/BasicUserDetailsQuery.ts
  src/resolvers/queries/CallQuery.ts
  src/resolvers/queries/GetPageContentQuery.ts
  src/resolvers/queries/ProposalStatusQuery.ts
  src/resolvers/queries/ProposalWorkflowQuery.ts
  src/resolvers/queries/UserQuery.ts
Labels: review: please, refactor

#718 feat: add logging on error
  package-lock.json
  package.json
  src/middlewares/graphql.ts
Labels: enhancement, review: please

#716 feat: Add PDF templates
  db_patches/0125_AddPdfTemplateAndLinkToCall.sql
  src/buildContext.ts
  src/config/Tokens.ts
  src/config/dependencyConfigE2E.ts
  src/config/dependencyConfigESS.ts
  src/config/dependencyConfigSTFC.ts
  src/config/dependencyConfigTest.ts
  src/context/index.ts
  src/datasources/PdfTemplateDataSource.ts
  src/datasources/mockups/CallDataSource.ts
  src/datasources/mockups/PdfTemplateDataSource.ts
  src/datasources/postgres/PdfTemplateDataSource.ts
  src/datasources/postgres/TemplateDataSource.ts
  src/datasources/postgres/records.ts
  src/models/Call.ts
  src/models/PdfTemplate.ts
  src/models/Template.ts
  src/mutations/CallMutations.spec.ts
  src/mutations/PdfTemplateMutations.spec.ts
  src/mutations/PdfTemplateMutations.ts
  src/mutations/TemplateMutations.spec.ts
  src/mutations/TemplateMutations.ts
  src/queries/PdfTemplateQueries.spec.ts
  src/queries/PdfTemplateQueries.ts
  src/resolvers/mutations/CreateCallMutation.ts
  src/resolvers/mutations/CreatePdfTemplateMutations.ts
  src/resolvers/mutations/DeletePdfTemplateMutation.ts
  src/resolvers/mutations/UpdateCallMutation.ts
  src/resolvers/mutations/UpdatePdfTemplateMutation.ts
  src/resolvers/queries/PdfTemplateQuery.ts
  src/resolvers/queries/PdfTemplatesQuery.ts
  src/resolvers/types/Call.ts
  src/resolvers/types/CommonWrappers.ts
  src/resolvers/types/PdfTemplate.ts
  src/resolvers/types/Template.ts
Labels: enhancement, review: please

#721 feature: Attach PDF template to call and pass to factory
  src/datasources/mockups/QuestionaryDataSource.ts
  src/datasources/postgres/CallDataSource.ts
  src/factory/pdf/proposal.ts
  src/models/ConditionEvaluator.ts
  src/models/ProposalModelFunctions.spec.ts
  src/models/ProposalModelFunctions.ts
  src/queries/PdfTemplateQueries.spec.ts
  src/queries/PdfTemplateQueries.ts
Labels: review: please, feature

#722 fix: Await user creation to prevent race conditions
  src/datasources/stfc/StfcUserDataSource.ts
Labels: bug, review: please

#711 refactor(graphql): refactor getMetadata endpoint to follow convention
  src/datasources/IFileDataSource.ts
  src/datasources/mockups/FileDataSource.ts
  src/datasources/postgres/FileDataSource.ts
  src/middlewares/files.ts
  src/queries/FileQueries.ts
  src/resolvers/queries/FileMetadataQuery.ts
  src/resolvers/queries/FilesMetadataQuery.ts
Labels: review: please, refactor

#723 feature: Add additional integer options
  package-lock.json
  package.json
  src/resolvers/types/FieldConfig.ts
Labels: feature
