Repository UserOfficeProject/user-office-backend, pull requests merged in 2022-07, with the labels that each got.

#692 refactor: import faker from fork UserOfficeProject/user-office-projec…
  package-lock.json
  package.json
  src/populate/dummy.ts
  src/populate/index.ts
Labels: review: please, refactor

#694 fix: Hotfix for STFC instrument assignment
  src/auth/StfcUserAuthorization.spec.ts
  src/auth/StfcUserAuthorization.ts
Labels: bug, review: please

#699 fix: Fix STFC email search
  src/datasources/stfc/StfcUserDataSource.spec.ts
  src/datasources/stfc/StfcUserDataSource.ts
  src/datasources/stfc/__mocks__/UOWSSoapInterface.ts
Labels: bug, review: please

#701 fix: Fix STFC email search
  src/auth/StfcUserAuthorization.ts
  src/datasources/stfc/StfcUserDataSource.spec.ts
  src/datasources/stfc/StfcUserDataSource.ts
  src/datasources/stfc/__mocks__/UOWSSoapInterface.ts
Labels: bug

#702 Mergeback after hotfix release 14/07/2022
  src/auth/StfcUserAuthorization.ts
  src/datasources/stfc/StfcUserDataSource.spec.ts
  src/datasources/stfc/StfcUserDataSource.ts
  src/datasources/stfc/__mocks__/UOWSSoapInterface.ts
Labels: review: please

#691 feat: Add seps to a call
  db_patches/0125_CreateCallHasSeps.sql
  src/datasources/SEPDataSource.ts
  src/datasources/mockups/SEPDataSource.ts
  src/datasources/postgres/CallDataSource.ts
  src/datasources/postgres/SEPDataSource.ts
  src/mutations/CallMutations.ts
  src/resolvers/mutations/CreateCallMutation.ts
  src/resolvers/mutations/UpdateCallMutation.ts
  src/resolvers/types/Call.ts
Labels: enhancement

#704 259 send email to engineer when callcreated
  src/eventHandlers/email/stfcEmailHandler.ts
Labels: ops: bis-app-settings, review: please

#693 feat: Filter calls by SEP and filter SEPs by call
  src/datasources/SEPDataSource.ts
  src/datasources/mockups/SEPDataSource.ts
  src/datasources/postgres/CallDataSource.ts
  src/datasources/postgres/SEPDataSource.ts
  src/queries/SEPQueries.spec.ts
  src/queries/SEPQueries.ts
  src/resolvers/queries/CallsQuery.ts
  src/resolvers/queries/SEPsQuery.ts
Labels: enhancement
