Repository UserOfficeProject/user-office-backend, pull requests merged in 2022-06, with the labels that each got.

#666 Allow empty string template descriptions
  src/datasources/postgres/TemplateDataSource.ts
Labels: review: please

#667 Remove duplicate proposals in instrument scientist view
  db_patches/0122_RevertAddCallInstrumentsToProposalView.sql
  src/datasources/postgres/ProposalDataSource.ts
  src/datasources/postgres/records.ts
  src/datasources/stfc/StfcProposalDataSource.ts
Labels: review: please

#660 feat: Add updateSettings endpoint for modifying settings
  src/config/ess/configureESSEnvironment.ts
  src/config/setTimezoneAndFormat.ts
  src/config/stfc/configureSTFCEnvironment.ts
  src/datasources/AdminDataSource.ts
  src/datasources/mockups/AdminDataSource.ts
  src/datasources/postgres/AdminDataSource.ts
  src/mutations/AdminMutations.spec.ts
  src/mutations/AdminMutations.ts
  src/resolvers/mutations/settings/UpdateFeaturesMutation.ts
  src/resolvers/mutations/settings/UpdateSettingMutation.ts
  src/resolvers/types/CommonWrappers.ts
Labels: enhancement, review: please

#674 fix: Fix SEP membership check
  src/auth/UserAuthorization.ts
Labels: bug, review: please

#663 fix(auth): updating user details on login
  src/auth/EssUserAuthorization.ts
Labels: bug

#672 fix: Prevent random STFC logouts by reducing UOWS requests
  .prettierignore
  package-lock.json
  package.json
  src/auth/StfcUserAuthorization.ts
  src/datasources/stfc/StfcUserDataSource.ts
  src/datasources/stfc/UOWSSoapInterface.ts
  src/datasources/stfc/__mocks__/UOWSSoapInterface.ts
Labels: bug, review: please

#661 fix: Check if recommendation in the SEP meeting decision is defined because it could be set to 0 which represents Unset
  src/datasources/postgres/SEPDataSource.ts
Labels: bug, review: please

#665 feat: Add proposals count to SEPs and SEP members
  src/datasources/SEPDataSource.ts
  src/datasources/mockups/SEPDataSource.ts
  src/datasources/postgres/SEPDataSource.ts
  src/resolvers/types/SEP.ts
  src/resolvers/types/SEPReviwers.ts
Labels: enhancement, review: please

#678 fix: Fix permission issues with isMemberOfSEP where we should send sepId instead of userId
  src/auth/UserAuthorization.ts
  src/queries/SEPQueries.ts
  src/resolvers/types/Instrument.ts
  src/resolvers/types/VisitRegistration.ts
Labels: bug

#670 chore: Upgrade validation package
  package-lock.json
  package.json
Labels: review: please, chore

#669 feat: Make SEPs and SEP Proposals visible to SEP_Reviewer
  src/datasources/ProposalDataSource.ts
  src/datasources/mockups/ProposalDataSource.ts
  src/datasources/postgres/ProposalDataSource.ts
  src/datasources/postgres/SEPDataSource.ts
  src/queries/SEPQueries.ts
Labels: enhancement, review: please

#682 fix: re-add empty line at the docker-compose file
  docker-compose.yml
Labels: bug

#662 fix(templates): Should be able to delete active template
  db_patches/0121_NullifyActiveTemplateReferences.sql
Labels: bug, review: please

#677 feat: Send notify emails to all SEP reviewers that has not submitted reviews 2 days before the SEP review end date
  db_patches/0123_AddSEPReviewNotificationSentFlag.sql
  src/asyncJobs/allAsyncJobs.ts
  src/asyncJobs/jobs/checkCallsSEPReviewEnded.ts
  src/asyncJobs/startAsyncJobs.ts
  src/datasources/SEPDataSource.ts
  src/datasources/mockups/SEPDataSource.ts
  src/datasources/postgres/ReviewDataSource.ts
  src/datasources/postgres/SEPDataSource.ts
  src/datasources/postgres/records.ts
  src/eventHandlers/email/essEmailHandler.ts
  src/events/applicationEvents.ts
  src/events/event.enum.ts
Labels: enhancement, review: please

#659 fix(questionary): fixing missing validation for question template relation
  db_patches/db_seeds/0005_Questions.sql
Labels: bug, review: please

#685 fix: grant reading users for access token
  src/auth/UserAuthorization.ts
Labels: bug

#671 feat: Add organizationId to the basic user details to be able to use it on the frontend
  src/datasources/mockups/UserDataSource.ts
  src/datasources/postgres/records.ts
  src/datasources/stfc/StfcUserDataSource.ts
  src/models/User.ts
  src/queries/UserQueries.ts
  src/resolvers/types/BasicUserDetails.ts
  src/resolvers/types/Proposal.ts
Labels: enhancement

#683 feat: Speed up STFC setup by caching UOWS results
  src/auth/StfcUserAuthorization.spec.ts
  src/auth/StfcUserAuthorization.ts
  src/datasources/UserDataSource.ts
  src/datasources/mockups/UserDataSource.ts
  src/datasources/postgres/UserDataSource.ts
  src/datasources/stfc/StfcUserDataSource.spec.ts
  src/datasources/stfc/StfcUserDataSource.ts
  src/utils/LRUCache.spec.ts
  src/utils/LRUCache.ts
  src/utils/__mocks__/LRUCache.ts
Labels: enhancement, review: please

#687 Release 23 06 2022
  db_patches/0121_NullifyActiveTemplateReferences.sql
  db_patches/0123_AddSEPReviewNotificationSentFlag.sql
  db_patches/db_seeds/0005_Questions.sql
  package-lock.json
  package.json
  src/asyncJobs/allAsyncJobs.ts
  src/asyncJobs/jobs/checkCallsSEPReviewEnded.ts
  src/asyncJobs/startAsyncJobs.ts
  src/auth/StfcUserAuthorization.spec.ts
  src/auth/StfcUserAuthorization.ts
  src/auth/UserAuthorization.ts
  src/datasources/ProposalDataSource.ts
  src/datasources/SEPDataSource.ts
  src/datasources/UserDataSource.ts
  src/datasources/mockups/ProposalDataSource.ts
  src/datasources/mockups/SEPDataSource.ts
  src/datasources/mockups/UserDataSource.ts
  src/datasources/postgres/ProposalDataSource.ts
  src/datasources/postgres/ReviewDataSource.ts
  src/datasources/postgres/SEPDataSource.ts
  src/datasources/postgres/UserDataSource.ts
  src/datasources/postgres/records.ts
  src/datasources/stfc/StfcUserDataSource.spec.ts
  src/datasources/stfc/StfcUserDataSource.ts
  src/eventHandlers/email/essEmailHandler.ts
  src/events/applicationEvents.ts
  src/events/event.enum.ts
  src/models/User.ts
  src/models/questionTypes/FileUpload.ts
  src/queries/SEPQueries.ts
  src/queries/UserQueries.ts
  src/resolvers/types/BasicUserDetails.ts
  src/resolvers/types/FieldConfig.ts
  src/resolvers/types/Proposal.ts
  src/utils/LRUCache.spec.ts
  src/utils/LRUCache.ts
  src/utils/__mocks__/LRUCache.ts
Labels: review: please

#688 fix(pdf file upload): Hotfix for unlimited PDF page limit
  src/models/questionTypes/FileUpload.ts
Labels: bug

#690 Mergeback after hotfix release
  README.md
  src/models/questionTypes/FileUpload.ts
Labels: review: please
