Repository UserOfficeProject/user-office-backend, pull requests merged in 2022-03, with the labels that each got.

#566 feat: Allow to unsubmit proposal
  src/auth/ProposalAuthorization.ts
  src/datasources/mockups/ProposalDataSource.ts
  src/datasources/mockups/ProposalSettingsDataSource.ts
  src/mutations/ProposalSettingsMutations.spec.ts
  src/queries/ProposalSettingsQueries.spec.ts
Labels: enhancement, review: please

#557 feat(units): improve units handling
  db_patches/0116_CreateQuantitiesTable.sql
  db_patches/0117_MigrateUnits.sql
  db_patches/db_seeds/0005_Questions.sql
  docker-compose.yml
  package-lock.json
  package.json
  src/datasources/AdminDataSource.ts
  src/datasources/mockups/AdminDataSource.ts
  src/datasources/postgres/AdminDataSource.ts
  src/datasources/postgres/TemplateDataSource.ts
  src/datasources/postgres/records.ts
  src/models/Quantity.ts
  src/models/Unit.ts
  src/models/questionTypes/Interval.ts
  src/models/questionTypes/NumberInput.ts
  src/mutations/AdminMutations.ts
  src/mutations/TemplateMutations.ts
  src/queries/AdminQueries.ts
  src/queries/QuestionaryQueries.ts
  src/resolvers/mutations/CreateUnitMutation.ts
  src/resolvers/mutations/DeleteUnitMutation.ts
  src/resolvers/queries/QuantitiesQuery.ts
  src/resolvers/types/FieldConfig.ts
  src/resolvers/types/Quantity.ts
  src/resolvers/types/Unit.ts
  src/utils/isSiConversionFormulaValid.ts
Labels: enhancement, review: please

#565 fix(proposal permissions): Add instrument manager to queries like instrument scientist
  src/datasources/postgres/CallDataSource.ts
  src/datasources/postgres/InstrumentDataSource.ts
  src/datasources/postgres/ProposalDataSource.ts
Labels: bug

#575 fix: Remove placeholder flag when a invited user creates an account
  src/mutations/UserMutations.ts
Labels: bug

#570 feat: Add visitStart and visitEnd dates
  db_patches/0117_AddVisitRegistrationStartEndDates.sql
  src/datasources/mockups/VisitDataSource.ts
  src/datasources/postgres/VisitDataSource.ts
  src/datasources/postgres/records.ts
  src/models/VisitRegistration.ts
  src/mutations/VisitMutations.ts
  src/resolvers/mutations/CreateVisitRegistrationMutation.ts
  src/resolvers/mutations/UpdateVisitRegistration.ts
  src/resolvers/types/VisitRegistration.ts
Labels: enhancement

#579 fix: add more logs to verify user error
  src/mutations/UserMutations.ts
Labels: bug

#588 chore: Automatically update feature branch when base branch changes
  .github/workflows/autoupdate.yaml
Labels: chore

#591 fix: disable autoupdate
  .github/workflows/autoupdate.yaml
Labels: bug

#592 Delete CODEOWNERS
  .github/CODEOWNERS
Labels: review: please

#562 feat(units): Import/export units
  src/buildContext.ts
  src/config/Tokens.ts
  src/config/dependencyConfigE2E.ts
  src/config/dependencyConfigESS.ts
  src/config/dependencyConfigSTFC.ts
  src/config/dependencyConfigTest.ts
  src/context/index.ts
  src/datasources/AdminDataSource.ts
  src/datasources/TemplateDataSource.ts
  src/datasources/UnitDataSource.ts
  src/datasources/mockups/AdminDataSource.ts
  src/datasources/mockups/UnitDataSource.ts
  src/datasources/postgres/AdminDataSource.ts
  src/datasources/postgres/TemplateDataSource.ts
  src/datasources/postgres/UnitDataSource.ts
  src/models/Template.ts
  src/models/Unit.ts
  src/mutations/AdminMutations.ts
  src/mutations/TemplateMutations.ts
  src/mutations/UnitMutations.ts
  src/queries/AdminQueries.ts
  src/queries/UnitQueries.ts
  src/resolvers/mutations/CreateUnitMutation.ts
  src/resolvers/mutations/DeleteUnitMutation.ts
  src/resolvers/mutations/ImportTemplateMutation.ts
  src/resolvers/mutations/ImportUnitsMutation.ts
  src/resolvers/mutations/ValidateUnitImportMutation.ts
  src/resolvers/queries/QuantitiesQuery.ts
  src/resolvers/queries/UnitsAsJsonQuery.ts
  src/resolvers/queries/UnitsQuery.ts
  src/resolvers/registerEnums.ts
  src/resolvers/types/CommonWrappers.ts
  src/resolvers/types/ConflictResolution.ts
  src/resolvers/types/QuestionComparison.ts
  src/resolvers/types/UnitComparison.ts
  src/resolvers/types/UnitsImportWithValidation.ts
Labels: enhancement, review: please

#571 feat(SEPs): allow User Officer and SEP Chair/Secretary to un-submit SEP review
  src/auth/UserAuthorization.ts
  src/datasources/ReviewDataSource.ts
  src/datasources/mockups/ReviewDataSource.ts
  src/datasources/mockups/UserDataSource.ts
  src/datasources/postgres/ReviewDataSource.ts
  src/mutations/ReviewMutations.ts
  src/mutations/SEPMutations.spec.ts
  src/mutations/SEPMutations.ts
  src/mutations/UserMutations.ts
  src/queries/ReviewQueries.ts
  src/queries/SEPQueries.ts
  src/resolvers/mutations/UpdateReviewMutation.ts
Labels: enhancement

#599 fix: Allow users to verify email after user update to avoid false error messages
  src/mutations/UserMutations.ts
Labels: bug

#586 feat: validate file upload types
  package-lock.json
  package.json
  src/models/ProposalModelFunctions.spec.ts
  src/models/ProposalModelFunctions.ts
  src/models/questionTypes/Boolean.ts
  src/models/questionTypes/Date.ts
  src/models/questionTypes/FileUpload.ts
  src/models/questionTypes/Interval.ts
  src/models/questionTypes/NumberInput.ts
  src/models/questionTypes/QuestionRegistry.ts
  src/models/questionTypes/RichTextInput.ts
  src/models/questionTypes/SampleDeclaration.ts
  src/models/questionTypes/SelectionFromOptions.ts
  src/models/questionTypes/TextInput.ts
  src/mutations/QuestionaryMutations.ts
Labels: enhancement, review: please

#596 feat: updating shipment label
  src/datasources/mockups/QuestionaryDataSource.ts
  src/factory/pdf/shipmentLabel.ts
  src/models/Shipment.ts
Labels: enhancement

#584 fix: boolean question filter not working
  db_patches/db_seeds/0005_Questions.sql
  src/datasources/postgres/ProposalDataSource.ts
Labels: bug, review: please

#568 Optimise user officer proposal table
  .gitignore
  src/datasources/AdminDataSource.ts
  src/datasources/ProposalDataSource.ts
  src/datasources/mockups/AdminDataSource.ts
  src/datasources/mockups/ProposalDataSource.ts
  src/datasources/postgres/AdminDataSource.ts
  src/datasources/postgres/ProposalDataSource.ts
  src/eventHandlers/proposalWorkflow.ts
  src/queries/ProposalQueries.ts
  src/resolvers/queries/ProposalsViewQuery.ts
Labels: review: please

#607 feat: add help page to front page of the user office
  src/datasources/postgres/AdminDataSource.ts
  src/models/Page.ts
Labels: enhancement, review: please

#583 fix: Small possibility of duplicated proposal_ids (UserOfficeProject/user-office-project-issue-tracker#299)
  db_patches/0118_AlterGenerateProposalShortcode.sql
Labels: bug, review: please

#587 Added STFC config for message broker
  src/config/dependencyConfigSTFC.ts
  src/eventHandlers/messageBroker.ts
  src/events/applicationEvents.ts
  src/events/event.enum.ts
  src/mutations/CallMutations.ts
Labels: review: please

#608 fix: remove alarming message
  src/eventHandlers/messageBroker.ts
Labels: bug

#601 feat: Add other organization to user update
  src/mutations/UserMutations.ts
  src/resolvers/mutations/UpdateUserMutation.ts
Labels: enhancement

#606 fix: send instrument shortcode to EAM
  src/factory/pdf/shipmentLabel.ts
  src/services/assetRegistrar/eam/api/createContainer.ts
  src/services/assetRegistrar/eam/requests/AddAssetEquipment.ts
Labels: bug

#597 refactor: Date and Datetime format standardization and use of luxon for datetime manipulation
  db_patches/0118_AddDateTimeFormatSetting.sql
  docker-compose.e2e.yml
  example.development.env
  package-lock.json
  package.json
  src/config/ess/configureESSEnvironment.ts
  src/config/setTimezone.ts
  src/config/setTimezoneAndFormat.ts
  src/config/stfc/configureSTFCEnvironment.ts
  src/datasources/UserDataSource.ts
  src/datasources/mockups/ScheduledEventDataSource.ts
  src/datasources/mockups/UserDataSource.ts
  src/datasources/postgres/UserDataSource.ts
  src/datasources/postgres/records.ts
  src/datasources/stfc/StfcUserDataSource.ts
  src/factory/util.ts
  src/middlewares/graphql.ts
  src/models/Settings.ts
  src/models/User.ts
  src/models/questionTypes/Date.ts
  src/models/questionTypes/FileUpload.ts
  src/mutations/UserMutations.ts
  src/populate/index.ts
  src/resolvers/CustomScalars.ts
  src/resolvers/mutations/CreateUserMutation.ts
  src/resolvers/mutations/UpdateUserMutation.ts
  src/resolvers/queries/ScheduledEventsCoreQuery.ts
  src/resolvers/registerEnums.ts
  src/resolvers/types/ProposalBooking.ts
  src/resolvers/types/ScheduledEvent.ts
  src/resolvers/types/User.ts
Labels: enhancement, review: please, refactor

#585 Add dependency injection for external authentication
  src/auth/StfcUserAuthorization.spec.ts
  src/auth/StfcUserAuthorization.ts
  src/auth/UserAuthorization.ts
  src/auth/mockups/UserAuthorization.ts
  src/config/Tokens.ts
  src/config/dependencyConfigE2E.ts
  src/config/dependencyConfigESS.ts
  src/config/dependencyConfigSTFC.ts
  src/config/dependencyConfigTest.ts
  src/datasources/UserDataSource.ts
  src/datasources/postgres/UserDataSource.ts
  src/datasources/stfc/StfcUserDataSource.spec.ts
  src/datasources/stfc/StfcUserDataSource.ts
  src/middlewares/graphql.ts
  src/mutations/UserMutations.ts
  src/queries/ProposalSettingsQueries.ts
Labels: review: please

#611 feat: Send INSTRUMENT_DELETED event to the scheduler when instrument is removed
  src/eventHandlers/messageBroker.ts
  src/events/applicationEvents.ts
  src/events/event.enum.ts
  src/mutations/InstrumentMutations.ts
  src/resolvers/types/Instrument.ts
Labels: enhancement, review: please
