Repository UserOfficeProject/user-office-backend, pull requests merged in 2022-09, with the labels that each got.

#698 feat: Add predefined_messages table and expose CRUD endpoints
  db_patches/0125_AddPredefinedMessagesTable.sql
  src/buildContext.ts
  src/config/Tokens.ts
  src/config/dependencyConfigE2E.ts
  src/config/dependencyConfigESS.ts
  src/config/dependencyConfigSTFC.ts
  src/config/dependencyConfigTest.ts
  src/context/index.ts
  src/datasources/PredefinedMessageDataSource.ts
  src/datasources/mockups/PredefinedMessageDataSource.ts
  src/datasources/postgres/PredefinedMessageDataSource.ts
  src/datasources/postgres/records.ts
  src/events/event.enum.ts
  src/models/PredefinedMessage.ts
  src/models/ProposalModelFunctions.ts
  src/mutations/PredefinedMessageMutations.ts
  src/queries/PredefinedMessageQueries.ts
  src/resolvers/mutations/predefinedMessages/CreatePredefinedMessageMutation.ts
  src/resolvers/mutations/predefinedMessages/DeletePredefinedMessageMutation.ts
  src/resolvers/mutations/predefinedMessages/UpdatePredefinedMessageMutation.ts
  src/resolvers/queries/PredefinedMessageQuery.ts
  src/resolvers/types/CommonWrappers.ts
  src/resolvers/types/PredefinedMessage.ts
Labels: enhancement, review: please

#727 Use flat directory structure for emails
  src/eventHandlers/MailService/SMTPMailService.ts
Labels: review: please

#709 refactor(graphql): rename getPageContent to pageContent
  src/resolvers/queries/PageContentQuery.ts
Labels: review: please, refactor
