Repository UserOfficeProject/user-office-backend, pull requests merged in 2022-01, with the labels that each got.

#529 fix(eam): Month in JS is 0-based but in C# 1-based
  src/services/eam/requests/AddAssetEquipment.ts
  src/services/eam/requests/AddCaseManagement.ts
Labels: bug

#530 Remove sensitive and verbose logs
  package-lock.json
  package.json
  src/datasources/stfc/StfcUserDataSource.spec.ts
  src/datasources/stfc/StfcUserDataSource.ts
  src/datasources/stfc/UOWSSoapInterface.ts
  src/datasources/stfc/__mocks__/UOWSSoapInterface.ts
  src/mutations/UserMutations.ts
Labels: review: please

#537 Pin Faker version to 5.5.3
  package.json
Labels: review: please

#532 fix(shipments): Send start, end dates to EAM
  db_patches/0115_AttachShipmentToScheduledEvent.sql
  src/datasources/ShipmentDataSource.ts
  src/datasources/postgres/ShipmentDataSource.ts
  src/datasources/postgres/records.ts
  src/factory/pdf/shipmentLabel.ts
  src/models/Shipment.ts
  src/mutations/ShipmentMutations.ts
  src/resolvers/mutations/CreateShipmentMutation.ts
  src/resolvers/queries/ShipmentsQuery.ts
  src/resolvers/types/ScheduledEvent.ts
  src/resolvers/types/Shipment.ts
  src/resolvers/types/Visit.ts
  src/services/eam/index.ts
  src/services/eam/requests/AddAssetEquipment.ts
  src/services/eam/requests/AddCaseManagement.ts
Labels: bug

#542 fix(scheduled-event): renaming scheduledEvent to scheduledEventCore
  src/auth/EsiAuthorization.ts
  src/datasources/ScheduledEventDataSource.ts
  src/datasources/mockups/ScheduledEventDataSource.ts
  src/datasources/postgres/ScheduledEventDataSource.ts
  src/mutations/FeedbackMutations.ts
  src/mutations/ProposalEsiMutations.ts
  src/mutations/VisitMutations.ts
  src/queries/ScheduledEventQueries.ts
  src/resolvers/queries/ScheduledEventsCoreQuery.ts
  src/resolvers/types/ExperimentSafetyInput.ts
  src/services/eam/index.ts
Labels: bug

#543 fix: Users with many proposals cannot login
  src/decorators/Authorized.ts
  src/middlewares/graphql.ts
  src/models/User.ts
Labels: bug, review: please

#546 fix(typescript): Fix typing issues
  src/datasources/postgres/FileDataSource.ts
Labels: bug

#518 Upgrade and remove unused dependencies to reduce vulnerabilities
  .github/workflows/test-build.yml
  .npmrc
  Dockerfile
  Dockerfile.dev
  package-lock.json
  package.json
  src/customTypes/index.d.ts
  src/datasources/postgres/FileDataSource.ts
  src/middlewares/factory.ts
  src/middlewares/factory/pdf.ts
  src/middlewares/factory/xlsx.ts
  src/middlewares/graphql.ts
  src/utils/buildFederatedSchema.ts
Labels: review: please

#549 Run dev Docker container as Node user
  Dockerfile.dev
Labels: review: please

#551 fix: instrument sci unable to filter by question
  src/datasources/stfc/StfcProposalDataSource.ts
Labels: bug, review: please

#480 fix: GDPR concerns exposed over GraphQL
  src/auth/UserAuthorization.ts
  src/datasources/ProposalDataSource.ts
  src/datasources/SEPDataSource.ts
  src/datasources/VisitDataSource.ts
  src/datasources/mockups/ProposalDataSource.ts
  src/datasources/mockups/SEPDataSource.ts
  src/datasources/mockups/VisitDataSource.ts
  src/datasources/postgres/ProposalDataSource.ts
  src/datasources/postgres/SEPDataSource.ts
  src/datasources/postgres/VisitDataSource.ts
  src/factory/pdf/proposal.ts
  src/queries/UserQueries.spec.ts
  src/queries/UserQueries.ts
  src/resolvers/types/EventLog.ts
Labels: review: please

#539 SWAP-2147-cleanup-scheduler-when-proposal-removed
  src/eventHandlers/messageBroker.ts
  src/events/applicationEvents.ts
  src/events/event.enum.ts
  src/mutations/ProposalMutations.ts
Labels: enhancement

#550 fix: As a developer i want meaning full logs (Swap-2197)
  index.ts
  package-lock.json
  package.json
  src/asyncJobs/jobs/checkCallsSEPReviewEnded.ts
  src/auth/questionary/GenericTemplateQuestionaryAuthorizer.ts
  src/auth/questionary/SampleDeclarationQuestionaryAuthorizer.ts
  src/auth/questionary/ShipmentDeclarationQuestionaryAuthorizer.ts
  src/config/Tokens.ts
  src/config/dependencyConfigE2E.ts
  src/config/dependencyConfigESS.ts
  src/config/dependencyConfigSTFC.ts
  src/config/dependencyConfigTest.ts
  src/config/ess/configureGrayLogLogger.ts
  src/datasources/postgres/database.ts
  src/services/eam/index.ts
Labels: enhancement
