Repository UserOfficeProject/user-office-backend, pull requests merged in 2022-04, with the labels that each got.

#618 fix: SEP reviewer should only read/write reviews he/she can review
  src/auth/ProposalAuthorization.ts
  src/auth/ReviewAuthorization.ts
  src/auth/TechnicalReviewAuthorization.ts
  src/mutations/ReviewMutations.ts
  src/queries/ReviewQueries.ts
  src/resolvers/queries/ReviewQuery.ts
Labels: bug

#619 fix(review): Make grade proposal mandatory
  package-lock.json
  package.json
Labels: bug

#621 fix: review must have grade when submitting
  src/mutations/ReviewMutations.ts
  src/resolvers/mutations/SubmitProposalsReviewMutation.ts
Labels: bug

#602 feat: Bulk submit technical reviews
  package-lock.json
  package.json
  src/mutations/ReviewMutations.ts
  src/resolvers/mutations/SubmitTechnicalReviewMutation.ts
Labels: enhancement, review: please

#626 fix(technical reviews): Hotfix for review authorization and validation
  src/auth/ReviewAuthorization.ts
  src/mutations/ReviewMutations.ts
Labels: bug

#625 Added option for different rabbitmq vhost
  src/eventHandlers/messageBroker.ts
Labels: ops: bis-app-settings, review: please

#576 feat: Show experiment times
  src/datasources/ScheduledEventDataSource.ts
  src/datasources/mockups/ScheduledEventDataSource.ts
  src/datasources/postgres/ProposalEsiDataSource.ts
  src/datasources/postgres/ScheduledEventDataSource.ts
  src/factory/pdf/shipmentLabel.ts
  src/models/VisitRegistration.ts
  src/models/questionTypes/FileUpload.ts
  src/mutations/VisitMutations.ts
  src/queries/ScheduledEventQueries.ts
  src/queries/VisitQueries.ts
  src/resolvers/queries/ScheduledEventsCoreQuery.ts
  src/resolvers/registerEnums.ts
  src/resolvers/types/ScheduledEvent.ts
  src/resolvers/types/VisitRegistration.ts
Labels: enhancement

#513 feat: Add country to institution
  .github/CODEOWNERS
  db_patches/0114_AddCountryToInstitutions.sql
  src/datasources/AdminDataSource.ts
  src/datasources/mockups/AdminDataSource.ts
  src/datasources/postgres/AdminDataSource.ts
  src/datasources/postgres/records.ts
  src/models/Entry.ts
  src/models/Institution.ts
  src/mutations/AdminMutations.spec.ts
  src/mutations/AdminMutations.ts
  src/queries/AdminQueries.ts
  src/resolvers/mutations/CreateInstitutionsMutation.ts
  src/resolvers/mutations/UpdateInstitutionsMutation.ts
  src/resolvers/types/Fields.ts
  src/resolvers/types/Institution.ts
Labels: enhancement

#627 fix: Use null instead of 0 for sep proposals call filtering when we want to query all calls
  src/datasources/SEPDataSource.ts
  src/datasources/mockups/SEPDataSource.ts
  src/datasources/postgres/SEPDataSource.ts
  src/queries/SEPQueries.ts
  src/resolvers/queries/SEPQuery.ts
Labels: bug

#629 Release 14 04 2022
  .github/CODEOWNERS
  db_patches/0114_AddCountryToInstitutions.sql
  package-lock.json
  package.json
  src/auth/ReviewAuthorization.ts
  src/datasources/AdminDataSource.ts
  src/datasources/ScheduledEventDataSource.ts
  src/datasources/mockups/AdminDataSource.ts
  src/datasources/mockups/ScheduledEventDataSource.ts
  src/datasources/postgres/AdminDataSource.ts
  src/datasources/postgres/ProposalEsiDataSource.ts
  src/datasources/postgres/ScheduledEventDataSource.ts
  src/datasources/postgres/records.ts
  src/eventHandlers/messageBroker.ts
  src/factory/pdf/shipmentLabel.ts
  src/models/Entry.ts
  src/models/Institution.ts
  src/models/VisitRegistration.ts
  src/models/questionTypes/FileUpload.ts
  src/mutations/AdminMutations.spec.ts
  src/mutations/AdminMutations.ts
  src/mutations/ReviewMutations.ts
  src/mutations/VisitMutations.ts
  src/queries/AdminQueries.ts
  src/queries/ScheduledEventQueries.ts
  src/queries/VisitQueries.ts
  src/resolvers/mutations/CreateInstitutionsMutation.ts
  src/resolvers/mutations/SubmitProposalsReviewMutation.ts
  src/resolvers/mutations/SubmitTechnicalReviewMutation.ts
  src/resolvers/mutations/UpdateInstitutionsMutation.ts
  src/resolvers/queries/ScheduledEventsCoreQuery.ts
  src/resolvers/registerEnums.ts
  src/resolvers/types/Fields.ts
  src/resolvers/types/Institution.ts
  src/resolvers/types/ScheduledEvent.ts
  src/resolvers/types/VisitRegistration.ts
Labels: review: please

#617 Speed up getting templates in STFC mode
  src/decorators/Authorized.ts
Labels: review: please, refactor

#616 feat: hide technical review and instrument management features
  db_patches/0119_AddInstrumentScientistFeatures.sql
  src/config/ess/configureESSEnvironment.ts
  src/models/Feature.ts
Labels: enhancement, review: please

#628 feat: Add reviewer in the ProposalsFilter to be able to filter only logged in user reviews
  src/datasources/postgres/ProposalDataSource.ts
  src/models/Review.ts
  src/mutations/SEPMutations.ts
  src/resolvers/queries/ProposalsQuery.ts
Labels: enhancement, review: please

#633 chore: Update validation package version
  package-lock.json
  package.json
Labels: review: please, chore

#637 fix: Fixing possible race condition when calling resetDB
  src/mutations/AdminMutations.ts
Labels: bug, review: please

#640 fix: Enable to use EAM production environment
  example.development.env
  src/services/assetRegistrar/eam/api/createContainer.ts
  src/services/assetRegistrar/eam/api/createTicket.ts
  src/services/assetRegistrar/eam/api/getToken.ts
  src/services/assetRegistrar/eam/requests/AddAssetEquipment.ts
  src/services/assetRegistrar/eam/requests/AddCaseManagement.ts
  src/services/assetRegistrar/eam/utils/getEnvOrThrow.ts
  src/services/assetRegistrar/eam/utils/performApiRequest.ts
Labels: bug

#643 fix: adding reason why query error happened
  src/datasources/postgres/database.ts
Labels: bug
