Repository UserOfficeProject/user-office-backend, pull requests merged in 2022-05, with the labels that each got.

#635 feat: Remove access for SEP chair and secretary to un-submit or change submitted reviews
  src/auth/ReviewAuthorization.ts
  src/datasources/mockups/ReviewDataSource.ts
  src/datasources/mockups/UserDataSource.ts
  src/mutations/ReviewMutations.spec.ts
  src/mutations/ReviewMutations.ts
Labels: enhancement, review: please

#648 fix: This PR fixes dangling references in question_dependencies
  db_patches/0120_AddQuestionDependenciesOnDeleteCascade.sql
Labels: bug

#647 feat: Run an antivirus scan on uploaded files
  package-lock.json
  package.json
  src/models/questionTypes/FileUpload.ts
Labels: enhancement, review: please

#649 hotfix: db patch issue
  db_patches/0120_AddQuestionDependenciesOnDeleteCascade.sql
Labels: hotfix

#639 feat: Allow beamline manager to be able to do technical review on a proposal that is assigned to his instrument
  src/auth/ProposalAuthorization.ts
  src/auth/TechnicalReviewAuthorization.ts
  src/datasources/UserDataSource.ts
  src/datasources/mockups/UserDataSource.ts
  src/datasources/postgres/UserDataSource.ts
  src/datasources/stfc/StfcUserDataSource.ts
Labels: enhancement, review: please

#652 fix: mark default template after import
  src/mutations/TemplateMutations.ts
Labels: bug

#645 refactor: Move technical_review_assignee to the technical_review table and add technicalReviewAssignee resolver to technical review where we return user details
  db_patches/0120_AddTechnicalReviewAssigneeNameToProposalViewTable.sql
  src/auth/TechnicalReviewAuthorization.ts
  src/datasources/ProposalDataSource.ts
  src/datasources/mockups/ProposalDataSource.ts
  src/datasources/mockups/ReviewDataSource.ts
  src/datasources/postgres/ProposalDataSource.ts
  src/datasources/postgres/ReviewDataSource.ts
  src/datasources/postgres/records.ts
  src/factory/pdf/proposal.ts
  src/factory/xlsx/proposal.ts
  src/factory/xlsx/sep.ts
  src/models/Proposal.ts
  src/models/ProposalView.ts
  src/models/TechnicalReview.ts
  src/mutations/InstrumentMutations.ts
  src/mutations/ProposalMutations.ts
  src/mutations/ReviewMutations.ts
  src/resolvers/mutations/AddTechnicalReviewMutation.ts
  src/resolvers/mutations/UpdateTechnicalReviewAssignee.ts
  src/resolvers/types/CommonWrappers.ts
  src/resolvers/types/Proposal.ts
  src/resolvers/types/ProposalView.ts
  src/resolvers/types/TechnicalReview.ts
Labels: refactor

#644 fix: EAM expects SI values
  src/services/assetRegistrar/eam/api/createContainer.ts
Labels: bug

#650 feat(people table): Use orderBy and orderDirection to order users better when using the table column sort
  src/datasources/AdminDataSource.ts
  src/datasources/UserDataSource.ts
  src/datasources/mockups/AdminDataSource.ts
  src/datasources/mockups/UserDataSource.ts
  src/datasources/postgres/AdminDataSource.ts
  src/datasources/postgres/UserDataSource.ts
  src/datasources/stfc/StfcUserDataSource.ts
  src/mutations/UserMutations.ts
  src/queries/UserQueries.spec.ts
  src/queries/UserQueries.ts
  src/resolvers/mutations/CreateUserMutation.ts
  src/resolvers/mutations/UpdateUserMutation.ts
  src/resolvers/queries/UsersQuery.ts
  src/resolvers/types/Institution.ts
Labels: enhancement, review: please

#656 refactor(auth): Moving UserAuth into dependencies
  src/auth/EsiAuthorization.ts
  src/auth/FeedbackAuthorization.ts
  src/auth/ProposalAuthorization.ts
  src/auth/ReviewAuthorization.ts
  src/auth/SampleAuthorization.ts
  src/auth/ShipmentAuthorization.ts
  src/auth/TechnicalReviewAuthorization.ts
  src/auth/VisitAuthorization.ts
  src/auth/questionary/GenericTemplateQuestionaryAuthorizer.ts
  src/auth/questionary/SampleDeclarationQuestionaryAuthorizer.ts
  src/auth/questionary/ShipmentDeclarationQuestionaryAuthorizer.ts
  src/auth/questionary/VisitQuestionaryAuthorizer.ts
  src/buildContext.ts
  src/config/Tokens.ts
  src/context/index.ts
  src/middlewares/factory/xlsx.ts
  src/mutations/InstrumentMutations.ts
  src/mutations/ProposalEsiMutations.ts
  src/mutations/ProposalMutations.ts
  src/mutations/ReviewMutations.ts
  src/mutations/SEPMutations.ts
  src/mutations/SampleMutations.ts
  src/mutations/ShipmentMutations.ts
  src/mutations/VisitMutations.ts
  src/queries/CallQueries.ts
  src/queries/InstrumentQueries.ts
  src/queries/ProposalQueries.ts
  src/queries/ReviewQueries.ts
  src/queries/SEPQueries.ts
  src/queries/UserQueries.ts
Labels: refactor

#634 feat: send Rapid Access confirmation emails to the STFC User Office
  src/config/Tokens.ts
  src/config/dependencyConfigE2E.ts
  src/config/dependencyConfigESS.ts
  src/config/dependencyConfigSTFC.ts
  src/config/dependencyConfigTest.ts
  src/eventHandlers/MailService/SMTPMailService.ts
  src/eventHandlers/email.ts
  src/eventHandlers/email/essEmailHandler.ts
  src/eventHandlers/email/stfcEmailHandler.ts
  src/eventHandlers/index.ts
Labels: enhancement, review: please

#632 Sub templates imports and scripts to import templates
  README.md
  db_patches/0120_CleanupGenericTemplateQuestionaryDataAfterDelete.sql
  src/auth/UserAuthorization.ts
  src/datasources/TemplateDataSource.ts
  src/datasources/mockups/TemplateDataSource.ts
  src/datasources/postgres/TemplateDataSource.ts
  src/models/Template.ts
  src/mutations/ProposalMutations.ts
  src/mutations/TemplateMutations.ts
  src/queries/TemplateQueries.ts
  src/resolvers/mutations/ImportTemplateMutation.ts
  src/resolvers/mutations/ValidateTemplateImportMutation.ts
  src/resolvers/types/CommonWrappers.ts
  src/resolvers/types/TemplateImportWithValidation.ts
  src/resolvers/types/TemplateValidation.ts
  src/resolvers/types/TemplateValidationData.ts
Labels: review: please

#654 feat: Add ability to un-impersonate user after it gets impersonated
  src/middlewares/graphql.ts
  src/models/User.ts
  src/mutations/UserMutations.ts
Labels: enhancement, review: please

#657 feat(auth): As a user I want single sign on with PING
  src/auth/EssUserAuthorization.ts
  src/auth/StfcUserAuthorization.ts
  src/auth/UserAuthorization.ts
  src/auth/mockups/UserAuthorization.ts
  src/config/dependencyConfigE2E.ts
  src/config/dependencyConfigESS.ts
  src/datasources/postgres/UserDataSource.ts
  src/mutations/UserMutations.ts
Labels: enhancement, review: please

#655 feat: Add features page with possibility to enable and disable features
  src/datasources/AdminDataSource.ts
  src/datasources/mockups/AdminDataSource.ts
  src/datasources/postgres/AdminDataSource.ts
  src/models/Feature.ts
  src/mutations/AdminMutations.ts
  src/resolvers/mutations/settings/UpdateFeaturesMutation.ts
  src/resolvers/registerEnums.ts
  src/resolvers/types/CommonWrappers.ts
Labels: enhancement, review: please

#653 #234 Add linter workflow
  .eslintignore
  .github/workflows/lint.yml
  .prettierignore
  api_tests/environment.json
  api_tests/tests.json
  dev-commands/crudHelper.js
  dev-commands/generateDataSources.js
  dev-commands/generateModelsAndResolvers.js
  dev-commands/generateQueriesAndMutations.js
  dev-commands/templates/dataSourcesTemplates.js
  dev-commands/templates/modelAndResolversTemplates.js
  dev-commands/templates/queriesAndMutationsTemplates.js
  src/datasources/stfc/UOWSSoapInterface.ts
Labels: enhancement, review: please

#658 feat: Enable instrument management for STFC
  db_patches/0121_AddCallInstrumentsToProposalView.sql
  src/auth/StfcUserAuthorization.spec.ts
  src/auth/StfcUserAuthorization.ts
  src/config/dependencyConfigSTFC.ts
  src/config/stfc/configureSTFCEnvironment.ts
  src/datasources/InstrumentDataSource.ts
  src/datasources/mockups/InstrumentDataSource.ts
  src/datasources/postgres/InstrumentDataSource.ts
  src/datasources/postgres/ProposalDataSource.ts
  src/datasources/postgres/records.ts
  src/datasources/stfc/StfcCallDataSource.ts
  src/datasources/stfc/StfcProposalDataSource.ts
  src/datasources/stfc/StfcUserDataSource.ts
Labels: enhancement, ops: comms, ops: manual, review: please
